
#dubbox 配置
spring.dubbo:
  #表示要扫描的package目录
  scan: com.mob.demo
  #应用名称标识
  application:
    name: mob-demo-service
  #注册中心地址，可以配置多个zookeeper地址
  registry:
    address: zookeeper://localcentos:2181
  #dubbo协议，用于服务间直连通信
  dubbo-protocol:
    port: 20881
  #restful协议，用于http第三方调用
  rest-protocol:
    port: 8081
    server: tomcat



#druid 数据源配置
spring:
    datasource:
        url: jdbc:mysql://192.168.180.86:3306/sharesdk
        username: root
        password: lin12345
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver


#mybatis 配置
mybatis:
  mapperLocations: classpath:mapper/*.xml


#mongo 配置
spring.data.mongodb:
  database: test
  #authentication-database # Authentication database name.
  host: cmovdev008
  port: 41000
#  field-naming-strategy: org.springframework.data.mapping.model.PropertyNameFieldNamingStrategy






