#spring boot
server.port: ${rest.port}

#dubbox 配置
spring.dubbo:
  #表示要扫描的package目录
  scan: com.mob.demo
  #应用名称标识
  application:
    name: mob-demo-service
  #注册中心地址，可以配置多个zookeeper地址
  registry:
    address: ${zk}
  #dubbo协议，用于服务间直连通信
  dubbo-protocol:
    port: 20881


#log4j2
logging.config:
  classpath:log4j2.xml
