
debug: true

#dubbox 配置
spring.dubbo:
  #表示要扫描的package目录
  scan: com.mob.demo
  #应用名称标识
  application:
    name: mob-demo-service
  #注册中心地址，可以配置多个zookeeper地址
  registry:
    address: ${zk}
  #dubbo协议，用于服务间直连通信
  dubbo-protocol:
    port: 20881
  #restful协议，用于http第三方调用
  rest-protocol:
    port: 8081
    server: tomcat



#druid 数据源配置
spring:
    datasource:
        url: jdbc:mysql://192.168.180.86:3306/sharesdk
        username: root
        password: lin12345
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver


#mybatis 配置
mybatis:
  mapperLocations: classpath:mapper/*.xml
#
#
##mongo 配置
#spring.data.mongodb:
#  database: test
#  #authentication-database # Authentication database name.
#  host: ${mongo.host}
#  port: ${mongo.port}
##  field-naming-strategy: org.springframework.data.mapping.model.PropertyNameFieldNamingStrategy


## mongo 多数据源集群
#mongodb:
#  default:
#    servers: 192.168.10.243:27000,192.168.10.245:27000
#  user:
#    servers: 192.168.10.243:27000,192.168.10.245:27000
#




#kafka 配置
spring.kafka:
  bootstrap-servers: localcentos:9092
  consumer.group-id: myGroup


#log4j2
logging.config:
  classpath:log4j2.xml

