#spring boot
server.port: ${rest.port}

#dubbox 配置
spring.dubbo:
  #表示要扫描的package目录
  scan: com.mob.demo
  #应用名称标识
  application:
    name: mob-demo-service
  #注册中心地址，可以配置多个zookeeper地址
  registry:
    address: ${zk}
  #dubbo协议，用于服务间直连通信
  dubbo-protocol:
    host: pay_duboho_servier
    port: ${dubbo.port}


#log4j2
logging.config:
  classpath:log4j2.xml


## rsa加解密参数自定义
mob.rsa:
  modules: 1dfd1d615cb891ce9a76f42d036af7fce5f8b8efaa11b2f42590ecc4ea4cff28f5f6b0726aeb76254ab5b02a58c1d5b486c39d9da1a58fa6ba2f22196493b3a4cbc283dcf749bf63679ee24d185de70c8dfe05605886c9b53e9f569082eabdf98c4fb0dcf07eb9bb3e647903489ff0b5d933bd004af5be4a1022fdda41f347f1
  private: 0fd8d13dc0fbf50afc2541bd95374355a60493e2b2683893db05212bea23745dd32ebc995cf3b88535a0efa0b1e961b0f896d534c263ea5127df090069a179793dd3c0fcdffee4b3d56ad86f12237bf9f94f1af938e46872fbc2ecfd3c656b1a395ed43c49d68ba097eb77b6ca916eef39fba6dfea8a0f87a932b46224a86d93
  public: 009cbd92ccef123be840deec0c6ed0547194c1e471d11b6f375e56038458fb18833e5bab2e1206b261495d7e2d1d9e5aa859e6d4b671a8ca5d78efede48e291a3f
  key-size: 1024

# shutdown hook

#启用shutdown
endpoints.shutdown.enabled: true
##禁用密码验证
endpoints.shutdown.sensitive: false


endpoints.health.sensitive: false  #actuator的health接口是否需要安全保证
endpoints.health.enabled: true

#
#server.compression.enabled: true
#server.compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain







#开启shutdown的安全验证
#endpoints.shutdown.sensitive=true
#
##验证用户名
#security.user.name=admin
#
##验证密码
#security.user.password=admin
##角色
#management.security.role=SUPERUSER
#
## 指定端口
#management.port=8081
#
## 指定地址
#management.address=127.0.0.1