
debug: true


#dubbox 配置
spring.dubbo:
  #表示要扫描的package目录
  scan: com.mob.demo
  #应用名称标识
  application:
    name: mob-demo-service
  #注册中心地址，可以配置多个zookeeper地址
  registry:
    address: ${zk}
  #dubbo协议，用于服务间直连通信
  dubbo-protocol:
    port: 20881
  #restful协议，用于http第三方调用
  rest-protocol:
    port: 8081
    server: tomcat



##kafka 配置
#spring.kafka:
#  bootstrap-servers: localcentos:9092
#  consumer.group-id: myGroup


#log4j2
logging.config:
  classpath:log4j2.xml


##druid 数据源配置
#spring:
#    datasource:
#        url: jdbc:mysql://10.18.97.56:3306/sharesdk
#        username: root
#        password: lin12345
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#
#
##mybatis 配置
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#


#
#redis.clusters:
#  default:
#    nodes: ${redis.default.nodes}
#    timeout: 3
#    maxAttempts: 3
#  user:
#    nodes: ${redis.user.nodes}
#
